### ISSUE TITLE
Choice of Programming Language

### ISSUE THREAD

**Issue by steinhkl** [steinhkl/tsgce#1]
As we are looking at mostly string based operations and some API calls I would - intuitively - suggest using Python which has very uncomplicated string handling and also, according to a quick google search, has various implementations of NLP which one could use to get started.

However I myself have not used Python for a while and understand if you feel uncomfortable using the language.

Please make suggestions and discuss advantages and disadvantages.

**Comment by raQai** [comment]
Apache also provides the OpenNLP framework.

**Comment by humpalum** [comment]
moved to 23.11.2017

**Comment by humpalum** [comment]
Seems like python is set in stone.
