### ISSUE TITLE
Error in with Ngrams

### ISSUE THREAD

**Issue by humpalum** [steinhkl/tsgce#13]
The "error_in" variable makes no sense as it is. 
I thought it should define the Index of the first element of the Index. 
For example:
Sentence: "The grey big dog walk away"

it should give something around:
```
{
            "error_in": 0,
            "ngram": [
                   "The",
                   "grey",
                   "big",
                   "dog"
                
            ]
        },
{
            "error_in": 3,
            "ngram": [
                   "dog",
                   "walk",
                   "away"                
            ]
        }

```
 Without the index of the ngram its kind of hard to check where the ngram is positioned. Of course i could write something to search it, but i think it would be better located in you function, as i think, you guys should have the value quite quickly.

What do you guys think?

**Comment by cronoik** [comment]
It is fixable without much effort, but do you want to fix it before the presentation on thursday? I'm unaware of what the second group has to adjust.

**Comment by humpalum** [comment]
Group 2 is doing nothing with ngrams. If you change it ASAP it may be possible for G2 to add the NGRAM  word mixing until thursday.

**Comment by rbikoni** [comment]
Which kind of data structure do you want -  Right now you get list of dicts, including a list of lists, with information of the n ngram in "error_in" and the containing ngrams ? 

Do you want that we replace the list of lists as a list of dicts, containing informations about the index based of the source sentence and n in ngram or something different?

**Comment by humpalum** [comment]
Just an Array that contains the ngrams like you can see it above. 

It sounds like you got it right with your last sentence. However, the size of n is not necessary, since i can get this parameter with a single .length and its a little bit less error-prone like that.

Also, to make it more clear what error_in is meant to be, you could name it error_at, to make it more obvious that this is the index of the ngram.

It could look like that:

```
"ngrams" :[
{
            "error_at": 0,
            "ngram": [
                   "The",
                   "grey",
                   "big",
                   "dog"
                
            ]
        },
{
            "error_at": 3,
            "ngram": [
                   "dog",
                   "walk",
                   "away"                
            ]
        }]
```

**Comment by cronoik** [comment]
I think the structure should be like this:
```
{
            "length": 1,
            "ngram": [
                {
                    "error_at": 1,
                    "ngram": [
                        "bla"
                    ]
                },
                {
                    "error_at": 2,
                    "ngram": [
                        "bla1"
                    ]
                },
                {
                    "error_at": 0,
                    "ngram": [
                        "bla2"
                    ]
                }
            ]
        },
....
```
Now it is possible to access only the 2-grams or 3-grams. Patch is already commited.

**Comment by humpalum** [comment]
OK for me, Thanks
