### ISSUE TITLE
Currently 2nd groups programm uses Python 2.7

### ISSUE THREAD

**Issue by humpalum** [steinhkl/tsgce#3]
Currently the 2nd groups programm depends on [pattern-en](https://www.clips.uantwerpen.be/pages/pattern-en#conjugation). This module however depends on Python 2.7 and does not support Python3+.

Since the firsts group programm is currently programmed in Python3 we need to make a decision. 

- Keep it like it is and just write a programm-startskript which doesnt care what version of python it runs.
- Downgrade firsts groups programm to python2
- Upgrade second groups programm to python3 and ditch pattern-en
- Similiar to first solution: Use python3 and "hack" the python 2 stuff inside: https://stackoverflow.com/a/44965570

What do you guys think?

**Comment by cronoik** [comment]
It seems like that there is no module out there that allows conjugation of verbs with python3... :( Did you have found one? In my opinion we should make a decission based on the version of python the third group will use.

**Comment by humpalum** [comment]
So i just pushed a kind of hacky Start programm with 720b6882cbe5d56d92381ef8c1e571f88ffa7d23 

It worked on my Windows, but it kind of depends on the paths of python.
Havent checked it for Linux Systems so far, but if i didn't got the paths wrong, it could work.

**Comment by rbikoni** [comment]
Maybe the groups can use an environment which they prefer, if we use some sort of _virtual environments_, which contain all dependencies (packages, interpreter, corpera, ...).
As an result, we don't need to care which versions the groups are using, as long as we are able to call the different virtual environments from our start script and identify the current os.

**Comment by rbikoni** [comment]
According to https://github.com/clips/pattern is available for python 3.6+ in the development branch.

**Comment by humpalum** [comment]
Changed 2nd Groups to python3. 
febff56a24cc9cae1cf818a089b2f9762692c833
