### ISSUE TITLE
ntlk.data.find doesn't find masc_tagged - need to manually unzip

### ISSUE THREAD

**Issue by steinhkl** [steinhkl/tsgce#5]
from check_checkedCorpera.py lines 41ff

    try:
        nltk.data.find("tokenizers/punkt")
        nltk.data.find("corpora/brown")
        nltk.data.find("corpora/masc_tagged.zip")

always results in failure and ntlk keeps trying to download new packages. 
when starting the download it always returns:

[nltk_data] Downloading package punkt to /home/klaus/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Anything we can do about that?

**Comment by rbikoni** [comment]
IMO in the final version of everything, we should place the needed _nltk_data_ in a subdirectory of the project, afterwards we are able to set a relative path to the _nltk_data_ from the python source code.

**Comment by steinhkl** [comment]
Good idea. Let's keep this issue open until then.

**Comment by steinhkl** [comment]
Looks like this is still a problem. 
nltk.download does not unzip the data but does need masc_tagged to be unzipped to find it.

See http://www.nltk.org/api/nltk.html#nltk.downloader.unzip

**Comment by steinhkl** [comment]
this is "fixed" now by adding a function "uglyunzip" to check_checkedCorpera.py
not very pretty but it works. If you want to make it prettier go ahead.
