### ISSUE TITLE
All google results are 1

### ISSUE THREAD

**Issue by humpalum** [steinhkl/tsgce#8]
Since 7b8eb1c23b4c7e52382cd2d8cc20914babac62bb all google results are set to 1

Example:
```
$ ./start.py "The children sing a song."
Performing the check
Function of second group will be called
[('The children sing a song.', 1), ('The children sings a song.', 1), ('The children singing a song.', 1), ('The children sung a song.', 1)]
```

**Comment by steinhkl** [comment]
This is the rate limit.
I can reproduce in h_da wifi but it still works in eduroam.
I "fixed" it by printing a clearer error message and returning -1 for the number of queries.
